server:
  port: 8001
spring:
  application:
    name: user-service

eureka:
  client:
    service-url:
      #defaultZone: http://localhost:6001/eureka
      defaultZone: http://localhost:7001/eureka

