server:
  port: 8002


spring:
  application:
    name: account-service

eureka:
  client:
    service-url:
      #defaultZone: http://localhost:6001/eureka
      defaultZone: http://localhost:7001/eureka