spring:
  application:
    name: account-service
  profiles:
    active: port-9002
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:6001/eureka
      defaultZone: http://localhost:7001/eureka
     
---
server:
  port: 8002
spring:
  config:
    activate:
      on-profile: port-8002
---

server:
  port: 7002
spring:
  config:
    activate:
      on-profile: port-7002
---

server:
  port: 9002
spring:
  config:
    activate:
      on-profile: port-9002