server:
  port: 8004
spring:
  application:
    name: permission-service

eureka:
  client:
    service-url:
      #defaultZone: http://localhost:6001/eureka
      defaultZone: http://localhost:7001/eureka