server:
  port: 6001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: userModule
          servceId: user-service
          uri: http://localhost:8001/
          predicates:
            - Path=/users/**
