spring:
  application:
    name: role-service
  profiles:
    active: port-8003
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:6001/eureka
      defaultZone: http://localhost:7001/eureka

---
spring:
  config:
    activate:
      on-profile: port-8003
server:
  port: 8003
  
---
spring:
  config:
    activate:
      on-profile: port-7003
server:
  port: 7003
  
---
spring:
  config:
    activate:
      on-profile: port-9003
server:
  port: 9003